#!/bin/sh
# NAS control-plane installer. Grows one capability per generalization
# phase; still missing OS/arch detection, prompts, and full idempotency
# (that's Phase 4). Currently handles: the shared config file, the USB
# automount script + udev rule, and the power-action sudoers rule.
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONF=/etc/nas-control-plane.conf
DEFAULT_CONF="$SCRIPT_DIR/config/nas-control-plane.conf.default"
SUDOERS_FILE=/etc/sudoers.d/nas-control-plane-power

if [ "$(id -u)" -ne 0 ]; then
    echo "Run this as root (it writes to /etc)." >&2
    exit 1
fi

if [ -f "$CONF" ]; then
    echo "$CONF already exists - leaving it alone."
else
    cp "$DEFAULT_CONF" "$CONF"
    echo "Wrote default config to $CONF"
fi

# shellcheck source=/dev/null
. "$CONF"
OWNER_UID="${OWNER_UID:-1000}"

install_usb_automount() {
    install -m 0755 "$SCRIPT_DIR/usb-automount" /usr/local/sbin/usb-automount
    install -m 0644 "$SCRIPT_DIR/99-usb-automount.rules" /etc/udev/rules.d/99-usb-automount.rules
    udevadm control --reload-rules
    echo "Installed usb-automount + udev rule, and reloaded udev rules."
}

install_power_sudoers() {
    # Resolve the real binary locations on this box rather than assuming
    # Debian's /usr/sbin/reboot and /usr/sbin/poweroff - some distros keep
    # these elsewhere. Falls back to the Debian path only if command -v
    # can't find one at all, so this never produces an empty rule.
    reboot_bin=$(command -v reboot || echo /usr/sbin/reboot)
    poweroff_bin=$(command -v poweroff || echo /usr/sbin/poweroff)

    tmp=$(mktemp)
    cat > "$tmp" <<EOF
# Lets the desktop shell (running as uid $OWNER_UID) restart or shut down
# this NAS from its System settings. Scoped to exactly these two commands -
# deliberately not a blanket NOPASSWD grant. Generated by install.sh; edit
# $CONF and re-run it instead of hand-editing this file.
#$OWNER_UID ALL=(root) NOPASSWD: $reboot_bin, $poweroff_bin
EOF

    # A malformed sudoers file can break sudo system-wide - never install one
    # that hasn't been validated first.
    if ! visudo -c -f "$tmp" >/dev/null 2>&1; then
        echo "Generated sudoers file failed validation - not installing it." >&2
        visudo -c -f "$tmp" >&2 || true
        rm -f "$tmp"
        exit 1
    fi

    install -m 0440 "$tmp" "$SUDOERS_FILE"
    rm -f "$tmp"
    echo "Installed $SUDOERS_FILE ($reboot_bin, $poweroff_bin)."
}

install_usb_automount
install_power_sudoers
